name: Run API tests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'api/**/*'
  pull_request:
    paths:
      - 'api/**/*'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Set up build scan
        id: setup-build-scan
        uses: bmuschko/setup-gradle-public-build-scan@v1
        with:
          tags: '["local-integ-test", "ubuntu-latest", "backend-engineer"]'
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp **/target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging