on:
  push:
    branches:
      - main
    paths:
      - 'api/**/*'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots -Ddevelocity.scan.termsOfUse.url=https://gradle.com/help/legal-terms-of-use -Ddevelocity.scan.termsOfUse.accept=true -Dscan.tag.backend-engineer -Dquarkus.container-image.registry=ghcr.io -Dquarkus.container-image.push=true -Dquarkus.container-image.build=true -Dquarkus.container-image.group=davidesalerno package
      - run: mkdir staging && cp **/target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: ./api/staging
        env:
          GITHUB_TOKEN: ${{ secrets.DS_GITHUB_TOKEN }}